language: node_js
node_js:
  - "node"
  - "0.12"
branches:
  only:
    - master
sudo: false
matrix:
  fast_finish: true
before_script:
  - chmod 555 ./server/keys/makecerts.sh
  - (cd server/keys && exec ./makecerts.sh 127.0.0.1)
